### PR TITLE
feat(outlines): generate scrivener-friendly opml

### PR DESCRIPTION
**Pull request by sethmerrick**
Not thrilled about the way I pulled in the opml-generator package, but could not find another way because of the way the package `module.exports = function`.

The OMPL generation code itself may benefit from a refactor, but it works. I can save the output as a .opml file, then import into Scrivener with results matching expectations.

### CODE REVIEW

**Comment by sethmerrick** [comment]
Bah, just noticed that at some point I had exposed the index of the `content.blocks.forEach()` loop, but didn't end up using it. Left `( block, i )` behind. Not sure if I should leave it alone, or if I should refactor, kill this pull request, then open a new one. ( or maybe there's a better way? )

**Comment by joshdmiller** [comment]
A couple of quick things:
1. if you make changes to a PR, you can always force-push to this branch and it will update the PR; no need to submit a new one.
2. I'm not sure why that complicated import is necessary; why doesn't `import opmlGen from 'opml-generator` work? If it doesn't, then you need not the relative path, but simply `import opmlGen from 'opml-generator/opml-generator'`.
3. With regard to the index, I don't care that much; if it bothers you, remove it. :-)

**Comment by sethmerrick** [comment]
1. `git push origin +opml` did the trick!
2. It works now. Yay! I won't bother speculating as to how I missed the mark earlier.
3. Index - removed.

**Comment by joshdmiller** [comment]
Cool. Now since these are related, let's collapse them into one commit using `git rebase -i HEAD~1` and using the fixup/squash feature.

**Comment by sethmerrick** [comment]
Ta-daaa! Once I did a `git config --global core.editor vim` and figured out to do `git rebase -i HEAD~2`, it was smooth sailing. :)

**Pull request merged**
